const APP = {
  SET_TITLE: 'SET_TITLE'
}

const USERS = {
  LOAD: 'USERS_LOAD',
  LOAD_SUCCESS: 'USERS_LOAD_SUCCESS',
  LOAD_FAIL: 'USERS_LOAD_FAIL',
};

const DETAILS = {
  LOAD: 'DETAILS_LOAD',
  LOAD_SUCCESS: 'DETAILS_LOAD_SUCCESS',
  LOAD_FAIL: 'DETAILS_LOAD_FAIL',
};

export { USERS, DETAILS, APP };
